### ISSUE TITLE
Converting CoffeeScript to JavaScript

### ISSUE THREAD

**Issue by oriSomething** [callodacity/comment-anchors#6]
CoffeeScript is on decline also in the Atom ecosystem. Also, it's easier to use JavaScript because you can just open the devTools in Atom.
I might even consider TypeScript/Flow so we'll got a nice autocomplete/type checking but, this is something I can understand might be too much.
Of course, No need to fix what works. But, I still, JavaScript can make it easier at least for me

**Comment by callodacity** [comment]
Is it really? If that's the case I'm glad that it is on the decline!

**Comment by callodacity** [comment]
If coffeescript is on the decline in the Atom ecosystem then that makes me glad! I never found it better than JavaScript in my experience.

**Comment by oriSomething** [comment]
I'll do it.
By the way, what say about we using [`prettier`](https://github.com/prettier/prettier)?

**Comment by callodacity** [comment]
Prettier sounds good 👍
