### ISSUE TITLE
The title is unescaped content

### ISSUE THREAD

**Issue by oriSomething** [callodacity/comment-anchors#7]
Which means there will unexpected result:

<img width="543" alt="screen shot 2017-07-17 at 21 00 50" src="https://user-images.githubusercontent.com/2685242/28282443-232c3274-6b33-11e7-899d-4f46c4f2768b.png">
<img width="264" alt="screen shot 2017-07-17 at 21 00 56" src="https://user-images.githubusercontent.com/2685242/28282444-232f7510-6b33-11e7-927a-9c7f72b839d2.png">

From what I've search there is no XSS vulnerability by this

***
#### Edit:

It happens because of [this](https://github.com/callodacity/comment-anchors/blob/master/lib/comment-anchors-view.coffee#L32) line

**Comment by callodacity** [comment]
Thanks 👍
